### ISSUE TITLE
Please upgrade to support rails 5

### ISSUE THREAD

**Issue by johngluckmdsol** [artemave/REST-assured#10]
```
rails (~> 5.1.2) was resolved to 5.1.2, which
depends on
      activerecord (= 5.1.2)

rest-assured (~> 2.2.0) was
resolved to 2.2.0, which
depends on
      activerecord (~> 4.0)```

**Comment by johngluckmdsol** [comment]
Also note, your gem configuration is not pulling the latest.  right now, if I run

`gem install rest-assured`
it pulls 0.10.0

**Comment by artemave** [comment]
Hi @johngluckmdsol , good point, I'll make sure it works with ar/as 5.

I don't really understand what is wrong with gem configuration though. I tried `gem install rest-assured` and it seems to be pulling the latest gem. Can you clarify?

**Comment by johngluckmdsol** [comment]
See what happens when you include it in a Gemfile.  It came down as 0.10.0 for me

**Comment by artemave** [comment]
Tried it on a fresh ruby project and it seems to be pulling the latest gem.
