### ISSUE TITLE
Delete all does not delete requests.

### ISSUE THREAD

**Issue by slukes** [artemave/REST-assured#11]
Deleting all doubles does not appar to delete the corresponding requests in the database which means that when you create another double you end up seeing the old requests since the numbering scheme appears to start again from 1.

Steps to reproduce:

```
rest-assured &
curl -d 'fullpath=%2Fapi' http://localhost:4578/doubles
curl http://localhost:4578/api
curl http://localhost:4578/doubles/1.json | jq .requests
```
At this point I see my request as would be expected:

```
[
  {
    "id": 1,
    "double_id": 1,
    "params": "{}",
    "body": ""
     ...
  }
]

```

Now delete all the doubles and create a new one

```
curl -X DELETE http://localhost:4578/doubles/all
curl -d 'fullpath=%2Fsomethingelse' http://localhost:4578/doubles
curl http://localhost:4578/somethingelse
curl http://localhost:4578/doubles/1.json | jq .requests
```

Now I should expect to only see my new request but actually I see the original one as well:

```
[
  {
    "id": 1,
    "double_id": 1,
    "params": "{}",
    "body": ""
...
  },
  {
    "id": 4,
    "double_id": 1,
    "params": "{}",
    "body": "",
    "created_at": "2018-02-26T19:43:17.941Z"
...
  }
]
```
So I think there are two problems.

1. The IDs of the doubles appear to get recycled - I'm not sure why but the code doesn't seem to explicity create the id field so I think this is some rails magic?  
2. The call back to delete the children of the original double is not happening.  I think this is because you use Models::Double.delete_all rather than Models::Double.destroy_all.  According to the documentation "... Be careful with relations though, in particular :dependent rules defined on associations are not honored ..." (https://apidock.com/rails/ActiveRecord/Base/delete_all/class)

Unless you have an objection I propose to change the delete_all to be destroy_all.

**Comment by artemave** [comment]
Nice catch! `destroy_all` seems like the right thing to do.

**Comment by slukes** [comment]
Thanks @artemave it took a fair bit of digging to figure out what the issue was! PR submitted :)

**Comment by artemave** [comment]
New version is pushed to rubygems. Thanks @slukes !
