### ISSUE TITLE
Delays

### ISSUE THREAD

**Issue by slukes** [artemave/REST-assured#7]
When testing an integration, it is often desirable to test what it would do if the remote end point is slow to respond or times out.  

In Java's Wiremock api this can be acheived quite simply as described on this page -  http://wiremock.org/docs/simulating-faults/. 

It would be good to have a similar ability in Rest-assured.  I imagine the syntax could look like this:

  `RestAssured::Double.create(:fullpath => url, :status => status, :content => content :delay => 500)`

Which would cause the server to sleep for 500ms and then respond as usual.

**Is this something that you would be willing to see added to the project?**

**Comment by artemave** [comment]
Seems like a useful thing. Yes, please :)

**Comment by artemave** [comment]
Implemented
